"""Deterministic, text-only copy of a Context Pack for use in AI chat.

Only pack markdown text is copied. Binary assets are never embedded, content
is never summarized or reordered, no files are modified, and no paths or user
directory information leak into the output.
"""

from __future__ import annotations

import json
from pathlib import Path, PurePosixPath

_COPY_TITLE = "# AI Context Pack\n\nGenerated by AI Material Preprocessor"
_ASSET_NOTE = (
    "Binary assets are not included; asset references point into the local pack "
    "and may not resolve elsewhere."
)


def _source_lines(payload: dict[str, object]) -> list[str]:
    raw = payload.get("sources")
    sources = [item for item in raw if isinstance(item, dict)] if isinstance(raw, list) else []
    lines: list[str] = []
    for source in sources:
        source_id = str(source.get("source_id") or "?")
        raw_display = str(source.get("display_name") or source_id).strip()
        display = raw_display.replace("\\", "/").rsplit("/", maxsplit=1)[-1] or source_id
        fmt = str(source.get("format") or "")
        level = str(source.get("provenance_level") or "document")
        lines.append(f"- {source_id} — {display} ({fmt}, provenance: {level})")
    return lines


def _pack_index(entry: dict[str, object]) -> int:
    value = entry.get("index")
    if isinstance(value, bool):
        raise ValueError("Context Pack has an invalid pack entry index.")
    if isinstance(value, int):
        index = value
    elif isinstance(value, str) and value.strip().isdigit():
        index = int(value)
    else:
        raise ValueError("Context Pack has an invalid pack entry index.")
    if index <= 0:
        raise ValueError("Context Pack has an invalid pack entry index.")
    return index


def _pack_path(pack_dir: Path, entry: dict[str, object]) -> Path:
    raw = str(entry.get("file") or "").replace("\\", "/")
    relative = PurePosixPath(raw)
    if (
        relative.is_absolute()
        or len(relative.parts) != 2
        or relative.parts[0] != "packs"
        or relative.suffix.casefold() != ".md"
    ):
        raise ValueError("Context Pack entry must reference a Markdown file under packs/.")
    root = pack_dir.resolve()
    path = (pack_dir / Path(*relative.parts)).resolve()
    if not path.is_relative_to(root):
        raise ValueError("Context Pack references content outside the pack.")
    return path


def _context_markdown(
    pack_dir: Path, payload: dict[str, object], pack_index: int | None
) -> list[str]:
    raw = payload.get("packs")
    packs = [item for item in raw if isinstance(item, dict)] if isinstance(raw, list) else []
    if isinstance(raw, list) and len(packs) != len(raw):
        raise ValueError("Context Pack has an invalid pack entry.")
    indexed = [(_pack_index(item), item) for item in packs]
    indexes = [index for index, _item in indexed]
    if len(indexes) != len(set(indexes)):
        raise ValueError("Context Pack contains a duplicate pack index.")
    if pack_index is not None:
        indexed = [item for item in indexed if item[0] == pack_index]
        if not indexed:
            raise ValueError(f"Context Pack {pack_index} was not found.")
    ordered = sorted(indexed, key=lambda item: item[0])
    blocks: list[str] = []
    for _index, pack in ordered:
        path = _pack_path(pack_dir, pack)
        if path.is_file():
            blocks.append(path.read_text(encoding="utf-8").rstrip())
    return blocks


def build_context_copy(pack_dir: Path, *, pack_index: int | None = None) -> str:
    manifest_path = pack_dir / "manifest.json"
    if not manifest_path.is_file():
        raise ValueError("Context Pack manifest is missing.")
    try:
        payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise ValueError("Context Pack manifest is invalid.") from exc
    if not isinstance(payload, dict):
        raise ValueError("Context Pack manifest is invalid.")
    if payload.get("package_type") != "ai_context_pack":
        raise ValueError("Not an AI Context Pack.")

    context = _context_markdown(pack_dir, payload, pack_index)
    if not context:
        raise ValueError("Context Pack contains no readable pack content.")
    sections = [
        _COPY_TITLE,
        "## Sources\n\n" + "\n".join(_source_lines(payload)),
        "## Context\n\n" + "\n\n".join(context),
        _ASSET_NOTE,
    ]
    return "\n\n".join(sections).rstrip() + "\n"
