"""Deterministic, text-only copy of a Context Pack for use in AI chat.

Only pack markdown text is copied. Binary assets are never embedded, content
is never summarized or reordered, no files are modified, and no paths or user
directory information leak into the output.
"""

from __future__ import annotations

import json
from pathlib import Path

_COPY_TITLE = "# AI Context Pack\n\nGenerated by AI Material Preprocessor"
_ASSET_NOTE = (
    "Binary assets are not included; asset references point into the local pack "
    "and may not resolve elsewhere."
)


def _source_lines(payload: dict[str, object]) -> list[str]:
    raw = payload.get("sources")
    sources = [item for item in raw if isinstance(item, dict)] if isinstance(raw, list) else []
    lines: list[str] = []
    for source in sources:
        source_id = str(source.get("source_id") or "?")
        display = str(source.get("display_name") or source_id)
        fmt = str(source.get("format") or "")
        level = str(source.get("provenance_level") or "document")
        lines.append(f"- {source_id} — {display} ({fmt}, provenance: {level})")
    return lines


def _context_markdown(
    pack_dir: Path, payload: dict[str, object], pack_index: int | None
) -> list[str]:
    raw = payload.get("packs")
    packs = [item for item in raw if isinstance(item, dict)] if isinstance(raw, list) else []
    if pack_index is not None:
        packs = [item for item in packs if int(item.get("index") or -1) == pack_index]
        if not packs:
            raise ValueError(f"Context Pack {pack_index} was not found.")
    ordered = sorted(packs, key=lambda item: int(item.get("index") or 0))
    root = pack_dir.resolve()
    blocks: list[str] = []
    for pack in ordered:
        relative = str(pack.get("file") or "")
        path = (pack_dir / relative).resolve()
        if not path.is_relative_to(root):
            raise ValueError("Context Pack references content outside the pack.")
        if path.is_file():
            blocks.append(path.read_text(encoding="utf-8").rstrip())
    return blocks


def build_context_copy(pack_dir: Path, *, pack_index: int | None = None) -> str:
    manifest_path = pack_dir / "manifest.json"
    if not manifest_path.is_file():
        raise ValueError("Context Pack manifest is missing.")
    try:
        payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise ValueError("Context Pack manifest is invalid.") from exc
    if not isinstance(payload, dict):
        raise ValueError("Context Pack manifest is invalid.")
    if payload.get("package_type") != "ai_context_pack":
        raise ValueError("Not an AI Context Pack.")

    context = _context_markdown(pack_dir, payload, pack_index)
    if not context:
        raise ValueError("Context Pack contains no readable pack content.")
    sections = [
        _COPY_TITLE,
        "## Sources\n\n" + "\n".join(_source_lines(payload)),
        "## Context\n\n" + "\n\n".join(context),
        _ASSET_NOTE,
    ]
    return "\n\n".join(sections).rstrip() + "\n"
