from __future__ import annotations

import json
from pathlib import Path

import pytest

from ai_material_preprocessor.services.context_copy import build_context_copy
from ai_material_preprocessor.services.context_pack import ContextBudget, create_context_pack
from ai_material_preprocessor.services.document_provenance import ProvenanceKind, SourceSpan


def _build_pack(
    tmp_path: Path,
    sources: list[tuple[str, str, tuple[SourceSpan, ...]]],
    *,
    budget: ContextBudget | None = None,
):
    contents = {
        f"source-{index:03d}": content
        for index, (_name, content, _spans) in enumerate(sources, start=1)
    }
    spans = {
        f"source-{index:03d}": value
        for index, (_name, _content, value) in enumerate(sources, start=1)
    }
    inputs: list[Path] = []
    for index, (name, _content, _spans) in enumerate(sources, start=1):
        source = tmp_path / "inputs" / name
        source.parent.mkdir(parents=True, exist_ok=True)
        source.write_text(f"original-{index}", encoding="utf-8")
        inputs.append(source)

    def processor(source: Path, source_id: str, source_root: Path) -> Path:
        package = source_root / source_id
        package.mkdir(parents=True)
        (package / "raw.md").write_text("raw", encoding="utf-8")
        (package / "content.md").write_text(contents[source_id], encoding="utf-8")
        (package / "manifest.json").write_text(
            json.dumps(
                {
                    "source": {"name": source.name, "format": source.suffix, "sha256": "a" * 64},
                    "provenance": [span.to_dict() for span in spans[source_id]],
                    "warnings": [],
                },
                ensure_ascii=False,
            ),
            encoding="utf-8",
        )
        return package

    return create_context_pack(
        sources=tuple(inputs),
        output_root=tmp_path / "outputs",
        budget=budget or ContextBudget(None),
        source_processor=processor,
    )


def _pdf_page() -> tuple[str, str, tuple[SourceSpan, ...]]:
    return (
        "lecture.pdf",
        "<!-- Page: 37 -->\n\nPDF paragraph.",
        (SourceSpan(ProvenanceKind.PAGE, "第 37 页", 37, 1, 3),),
    )


def _long_content() -> str:
    return "# Notes\n\n" + "\n\n".join(
        f"Section {index}. " + "word " * 230 for index in range(1, 13)
    )


def test_copy_is_deterministic_for_same_input(tmp_path: Path) -> None:
    result = _build_pack(tmp_path, [_pdf_page()])

    first = build_context_copy(result.output_dir)
    second = build_context_copy(result.output_dir)

    assert first == second
    assert first.endswith("\n")


def test_copy_includes_source_inventory_and_source_references(tmp_path: Path) -> None:
    result = _build_pack(
        tmp_path,
        [
            _pdf_page(),
            (
                "slides.pptx",
                "<!-- Slide number: 18 -->\n\nSlide content.",
                (SourceSpan(ProvenanceKind.SLIDE, "幻灯片 18", 18, 1, 3),),
            ),
        ],
    )

    text = build_context_copy(result.output_dir)

    assert "# AI Context Pack" in text
    assert "Generated by AI Material Preprocessor" in text
    assert "## Sources" in text
    assert "source-001 — lecture.pdf" in text
    assert "source-002 — slides.pptx" in text
    assert "## Source source-001" in text
    assert "## Source source-002" in text
    assert "PDF paragraph." in text


def test_copy_supports_single_pack_selection(tmp_path: Path) -> None:
    result = _build_pack(
        tmp_path, [("notes.txt", _long_content(), ())], budget=ContextBudget(1_000)
    )
    assert len(result.packs) >= 2

    full = build_context_copy(result.output_dir)
    assert "# Context Pack 1 of" in full
    assert "# Context Pack 2 of" in full

    single = build_context_copy(result.output_dir, pack_index=1)
    assert "# Context Pack 1 of" in single
    assert "# Context Pack 2 of" not in single


def test_copy_single_pack_missing_raises(tmp_path: Path) -> None:
    result = _build_pack(tmp_path, [_pdf_page()])

    with pytest.raises(ValueError, match="not found"):
        build_context_copy(result.output_dir, pack_index=9)


def test_copy_never_leaks_private_or_temporary_paths(tmp_path: Path) -> None:
    private_root = tmp_path / "private" / "user-home"
    result = _build_pack(private_root, [_pdf_page()])

    text = build_context_copy(result.output_dir)

    assert str(private_root.resolve()) not in text
    assert str(result.output_dir.resolve()) not in text


def test_copy_never_embeds_binary_assets(tmp_path: Path) -> None:
    result = _build_pack(tmp_path, [_pdf_page()])
    asset = result.output_dir / "sources" / "source-001" / "assets" / "secret.bin"
    asset.parent.mkdir(parents=True, exist_ok=True)
    asset.write_bytes(b"\x00\x01BINARYPAYLOAD\xff")

    text = build_context_copy(result.output_dir)

    assert "BINARYPAYLOAD" not in text
    assert "\x00" not in text


def test_copy_reads_legacy_pack_without_extra_files(tmp_path: Path) -> None:
    pack = tmp_path / "legacy-pack"
    packs_dir = pack / "packs"
    packs_dir.mkdir(parents=True)
    (packs_dir / "001-context.md").write_text(
        "## Source source-001 — old.md\n\nContent.", encoding="utf-8"
    )
    (pack / "manifest.json").write_text(
        json.dumps(
            {
                "package_type": "ai_context_pack",
                "context_pack_version": 1,
                "sources": [
                    {
                        "source_id": "source-001",
                        "display_name": "old.md",
                        "format": ".md",
                        "provenance_level": "document",
                    }
                ],
                "packs": [{"index": 1, "file": "packs/001-context.md"}],
            },
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )

    text = build_context_copy(pack)

    assert "old.md" in text
    assert "Content." in text


def test_copy_rejects_missing_or_wrong_manifest(tmp_path: Path) -> None:
    with pytest.raises(ValueError, match="manifest"):
        build_context_copy(tmp_path / "missing")

    wrong = tmp_path / "wrong"
    wrong.mkdir()
    (wrong / "manifest.json").write_text(
        json.dumps({"package_type": "ai_document_package"}), encoding="utf-8"
    )
    with pytest.raises(ValueError, match="Context Pack"):
        build_context_copy(wrong)


def test_copy_sanitizes_legacy_absolute_source_display_names(tmp_path: Path) -> None:
    pack = tmp_path / "legacy-private-path"
    packs_dir = pack / "packs"
    packs_dir.mkdir(parents=True)
    (packs_dir / "001-context.md").write_text("Safe content.", encoding="utf-8")
    private_path = r"C:\Users\Private\Documents\lesson.pdf"
    (pack / "manifest.json").write_text(
        json.dumps(
            {
                "package_type": "ai_context_pack",
                "sources": [
                    {
                        "source_id": "source-001",
                        "display_name": private_path,
                        "format": ".pdf",
                    }
                ],
                "packs": [{"index": 1, "file": "packs/001-context.md"}],
            }
        ),
        encoding="utf-8",
    )

    text = build_context_copy(pack)

    assert "lesson.pdf" in text
    assert private_path not in text
    assert r"C:\Users\Private" not in text


@pytest.mark.parametrize(
    "packs",
    [
        [{"index": "not-a-number", "file": "packs/001-context.md"}],
        [
            {"index": 1, "file": "packs/001-context.md"},
            {"index": 1, "file": "packs/001-context.md"},
        ],
        [{"index": 1, "file": "content.txt"}],
    ],
)
def test_copy_rejects_malformed_or_ambiguous_pack_entries(
    tmp_path: Path, packs: list[dict[str, object]]
) -> None:
    pack = tmp_path / "malformed"
    packs_dir = pack / "packs"
    packs_dir.mkdir(parents=True)
    (packs_dir / "001-context.md").write_text("Safe content.", encoding="utf-8")
    (pack / "content.txt").write_text("Wrong upload unit.", encoding="utf-8")
    (pack / "manifest.json").write_text(
        json.dumps({"package_type": "ai_context_pack", "sources": [], "packs": packs}),
        encoding="utf-8",
    )

    with pytest.raises(ValueError, match="pack entry|duplicate|Markdown"):
        build_context_copy(pack)
